[package]
name = "reverso-test"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
bootserver = { git = "https://github.com/oxidecomputer/boot-image-tools" }
rand = "0.9.2"
anyhow = "1.0.100"
